name: Redeem
main: keo\redeem\Main
version: 2.5.0
api: 5.0.0
author: keole
description: "Redeem ascending hcf"
    
permissions:
  redeem.command:
    default: true
  redeem.create:
    default: op
  redeem.edit:
    default: op
        