name: Redeem
main: keo\redeem\Main
version: 2.7.0
api: 5.0.0
author: keole
description: "Rewards to codes"
website: https://github.com/keolehub

permissions:
  redeem.command:
    default: true
  redeem.create:
    default: op
  redeem.edit:
    default: op
        